Student.create(first_name: "Sean", last_name: "Yi")
Student.create(first_name: "Jane", last_name: "White")
Student.create(first_name: "Maria", last_name: "Lopez")
Student.create(first_name: "Kevin", last_name: "Mark")
Student.create(first_name: "Jeff", last_name: "Phelps")
Student.create(first_name: "Duke", last_name: "Ko")
